---
# tasks file for solutiondrive.vault
- name: "Download Zip-Archive for version {{ vault_app_version }}"
  get_url:
    url: "{{ vault_app_url }}"
    dest: "{{ vault_app_download_location }}/{{ vault_app_zip }}"
    checksum: "{{ vault_app_checksum }}"

- name: "Unzip Vault Archive - {{ vault_app_version }}"
  unarchive:
    src: "{{ vault_app_download_location }}/{{ vault_app_zip }}"
    remote_src: yes
    dest: "/usr/local/bin"
    mode: "u+rwx"
    owner: solution
    creates: /usr/local/bin/vault

- name: "Create folder for holding configuration of the vault"
  file:
    path: "{{ vault_configuration_path }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rx"

- name: "Create configuration file based on template"
  template:
    src: vault_config.hcl.j2
    dest: "{{ vault_configuration_path }}/config.hcl"
    mode: "u=rwx,g=rwx,o=r"
